services:
  db:
    image: mysql:8.0
    container_name: go_social_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: go_social_api
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      API_PORT: ${API_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ENV: production
    ports:
      - "5000:5000"
    restart: always

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: go_social_webapp
    depends_on:
      - api
    environment:
      API_URL: http://api:5000
    ports:
      - "8080:8080"
    restart: always

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    command: [
      "-path", "/migrations",
      "-database", "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE}",
      "up"
    ]
    depends_on:
      - db

volumes:
  db_data: