FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o webapp

# Final image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/webapp .

EXPOSE 8080

CMD ["./webapp"]